/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Residency = {
  _id: string;
  _type: "residency";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organization: string;
  url?: string;
  role: string;
  date: string;
  orderRank?: string;
};

export type Exhibition = {
  _id: string;
  _type: "exhibition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  gallery: string;
  location: string;
  date: string;
};

export type CourseTaught = {
  _id: string;
  _type: "courseTaught";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  institution: string;
  program: string;
  format: string;
  location: string;
  date: string;
  url?: string;
  orderRank?: string;
};

export type Interview = {
  _id: string;
  _type: "interview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  organization: string;
  location: string;
  date: string;
  url?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type FeaturedProject = {
  _id: string;
  _type: "featuredProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  project: ProjectReference;
  orderRank?: string;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  url?: string;
};

export type CloudinaryImage = {
  _id: string;
  _type: "cloudinaryImage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cloudinaryKey?: string;
};

export type SpeakingEngagement = {
  _id: string;
  _type: "speakingEngagement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  event: string;
  location: string;
  date: string;
  url?: string;
  isNameTitle: boolean;
};

export type SocialMedia = {
  _id: string;
  _type: "socialMedia";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  platform?: string;
  url?: string;
  orderRank?: string;
};

export type PersonInfo = {
  _id: string;
  _type: "personInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
  title: string;
  year: string;
  tools: string;
  role: string;
  site?: string;
  primaryMedia: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  otherMedia?: Array<
    | {
        cloudinaryKey?: string;
        _type: "cloudinaryImage";
        _key: string;
      }
    | {
        url?: string;
        _type: "video";
        _key: string;
      }
  >;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Residency
  | Exhibition
  | CourseTaught
  | Interview
  | ProjectReference
  | FeaturedProject
  | Video
  | CloudinaryImage
  | SpeakingEngagement
  | SocialMedia
  | PersonInfo
  | Project
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/lib/queries.ts
// Variable: BIO_QUERY
// Query: *[_type == "personInfo"][0].bio
export type BIO_QUERY_RESULT = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}> | null;

// Source: sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $project][0]{'projectId': slug.current, content, title, year, role, tools, site, otherMedia}
export type PROJECT_QUERY_RESULT = {
  projectId: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  title: string;
  year: string;
  role: string;
  tools: string;
  site: string | null;
  otherMedia: Array<
    | {
        cloudinaryKey?: string;
        _type: "cloudinaryImage";
        _key: string;
      }
    | {
        url?: string;
        _type: "video";
        _key: string;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "featuredProject"]|order(orderRank){ "project": project->{'projectId': slug.current, title, primaryMedia} }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  project: {
    projectId: string;
    title: string;
    primaryMedia: string;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: SOCIALS_QUERY
// Query: *[_type == "socialMedia"]|order(orderRank)
export type SOCIALS_QUERY_RESULT = Array<{
  _id: string;
  _type: "socialMedia";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  platform?: string;
  url?: string;
  orderRank?: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: SPEAKING_ENGAGEMENTS_QUERY
// Query: *[_type == "speakingEngagement"]
export type SPEAKING_ENGAGEMENTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "speakingEngagement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  event: string;
  location: string;
  date: string;
  url?: string;
  isNameTitle: boolean;
}>;

// Source: sanity/lib/queries.ts
// Variable: INTERVIEWS_QUERY
// Query: *[_type == "interview"]
export type INTERVIEWS_QUERY_RESULT = Array<{
  _id: string;
  _type: "interview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  organization: string;
  location: string;
  date: string;
  url?: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: COURSES_TAUGHT_QUERY
// Query: *[_type == "courseTaught"]|order(orderRank)
export type COURSES_TAUGHT_QUERY_RESULT = Array<{
  _id: string;
  _type: "courseTaught";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  institution: string;
  program: string;
  format: string;
  location: string;
  date: string;
  url?: string;
  orderRank?: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: EXHIBITIONS_QUERY
// Query: *[_type == "exhibition"]
export type EXHIBITIONS_QUERY_RESULT = Array<{
  _id: string;
  _type: "exhibition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  gallery: string;
  location: string;
  date: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: RESIDENCY_QUERY
// Query: *[_type == "residency"]|order(orderRank)
export type RESIDENCY_QUERY_RESULT = Array<{
  _id: string;
  _type: "residency";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organization: string;
  url?: string;
  role: string;
  date: string;
  orderRank?: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "personInfo"][0].bio': BIO_QUERY_RESULT;
    "*[_type == \"project\" && slug.current == $project][0]{'projectId': slug.current, content, title, year, role, tools, site, otherMedia}": PROJECT_QUERY_RESULT;
    '*[_type == "featuredProject"]|order(orderRank){ "project": project->{\'projectId\': slug.current, title, primaryMedia} }': FEATURED_PROJECTS_QUERY_RESULT;
    '*[_type == "socialMedia"]|order(orderRank)': SOCIALS_QUERY_RESULT;
    '*[_type == "speakingEngagement"]': SPEAKING_ENGAGEMENTS_QUERY_RESULT;
    '*[_type == "interview"]': INTERVIEWS_QUERY_RESULT;
    '*[_type == "courseTaught"]|order(orderRank)': COURSES_TAUGHT_QUERY_RESULT;
    '*[_type == "exhibition"]': EXHIBITIONS_QUERY_RESULT;
    '*[_type == "residency"]|order(orderRank)': RESIDENCY_QUERY_RESULT;
  }
}
